config/routes.rb
Rails.application.routes.draw do
  get 'balance' => 'balance#index', as: :user_balance

  get 'balance/add'

  get 'balance/remove'
  patch 'balance' => 'balance#update'
  put 'balance' => 'balance#update'

  get 'search/results/' => 'search#results'

  get 'profile/edit' => 'profile#edit'
  get 'profile/:id' => 'profile#show', as: :profile
  get 'profile' => 'profile#redirect'
  patch 'profile/:id' => 'profile#update'

  resources :books do
    resources :reviews
  end
  
  post 'transactions/create/' => 'transactions#create'
  get 'transactions/return_book/' => 'transactions#return_book'
  
  get 'welcome/index'

  devise_for :users

  root 'welcome#index'

  get 'account' => 'account#home', as: :account_home
  resources :transactions

end

app/controllers/balance_controller.rb
class BalanceController < ApplicationController
  before_filter :authenticate_user!
  def index
    @balance = current_user.user_balance
    if !@balance then
      @balance = UserBalance.new
      current_user.user_balance = @balance
    end
  end

  def add
    @balance = current_user.user_balance
    if !@balance then
      @balance = UserBalance.new
      current_user.user_balance = @balance
    end
  end

  def remove
    @balance = current_user.user_balance
    if !@balance then
      @balance = UserBalance.new
      current_user.user_balance = @balance
    end
  end

  def update
    @balance = current_user.user_balance
    if !@balance then
      @balance = UserBalance.new
      current_user.user_balance = @balance
    end
    attributes = user_balance_params.clone
    # render :text => attributes[:update_type]
    if attributes['update_type'].eql? 'add' then
      attributes[:balance] = attributes[:balance].to_d + @balance.balance
    else
      attributes[:balance] = @balance.balance - attributes[:balance].to_d 
    end
    respond_to do |format|
      if @balance.update attributes.except(:update_type) then
        format.html { redirect_to @balance, notice: 'Funds were successfully updated.' }
        format.json { render :index, status: :ok, location: @balance }
      else
        format.html { render :add }
        format.json { render json: @balance.errors, status: :unprocessable_entity }
      end
    end
  end
  private
    # Using a private method to encapsulate the permissible parameters is just a good pattern
    # since you'll be able to reuse the same permit list between create and update. Also, you
    # can specialize this method with per-user checking of permissible attributes.
    def user_balance_params
      params.require(:user_balance).permit(:balance, :update_type)
    end
end

app/helpers/balance_helper.rb
module BalanceHelper
end

app/views/balance/add.html.erb
<h1>Add Funds to Balance</h1>
<h3>Current Balance: <%= number_to_currency(@balance.balance) %></h3>


<div class="row">
  <div class="col-sm-5">

    <%= form_for @balance, url: user_balance_path do |f| %>
      <% if @balance.errors.any? %>
        <div id="error_explanation text-danger">
          <h2><%= pluralize(@balance.errors.count, 'error') %> prohibited this book from being saved:</h2>

          <ul>
          <% @balance.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label(:balance, 'Funds To Add') %><br>
        <div class="input-group">
          <div class="input-group-addon">$</div>
          <%= f.text_field :balance, :value => '0.00', maxlength: 6, :class => 'form-control' %>
        </div>
      </div>
      <%= f.hidden_field 'update_type', :value => 'add' %>
      <div class="actions">
        <%= f.submit 'Add Funds', class: 'btn btn-primary' %>
        <%= link_to 'Back', user_balance_path, class: 'btn btn-warning' %>
      </div>
    <% end %>

  </div>
</div>

app/views/balance/index.html.erb
<h1>Balance</h1>
<h3>Current Balance: <%= number_to_currency(@balance.balance) %></h3>
<br>
<%= link_to 'Add Funds', balance_add_path, class: 'btn btn-primary' %>
<%= link_to 'Remove Funds', balance_remove_path, class: 'btn btn-danger' %>

app/views/balance/remove.html.erb
<h1>Remove Funds From Balance</h1>
<h3>Current Balance: <%= number_to_currency(@balance.balance) %></h3>


<div class="row">
  <div class="col-sm-5">

    <%= form_for @balance, url: user_balance_path do |f| %>
      <% if @balance.errors.any? %>
        <div id="error_explanation text-danger">
          <h2><%= pluralize(@balance.errors.count, 'error') %> prohibited this book from being saved:</h2>

          <ul>
          <% @balance.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label(:balance, 'Funds To Remove') %><br>
        <div class="input-group">
          <div class="input-group-addon">$</div>
          <%= f.text_field :balance, :value => '0.00', maxlength: 6, :class => 'form-control' %>
        </div>
      </div>
      <%= f.hidden_field 'update_type', :value => 'remove' %>
      <div class="actions">
        <%= f.submit 'Remove Funds', :class => 'btn btn-primary' %>
        <%= link_to 'Back', user_balance_path, class: 'btn btn-warning' %>
      </div>
    <% end %>

  </div>
</div>