config/routes.rb
Rails.application.routes.draw do
  get 'balance' => 'balance#index', as: :user_balance

  get 'balance/add'

  get 'balance/remove'
  patch 'balance' => 'balance#update'
  put 'balance' => 'balance#update'

  get 'search/results/' => 'search#results'

  get 'profile/edit' => 'profile#edit'
  get 'profile/:id' => 'profile#show', as: :profile
  get 'profile' => 'profile#redirect'
  patch 'profile/:id' => 'profile#update'

  resources :books do
    resources :reviews
  end
  
  post 'transactions/create/' => 'transactions#create'
  get 'transactions/return_book/' => 'transactions#return_book'
  
  get 'welcome/index'

  devise_for :users

  root 'welcome#index'

  get 'account' => 'account#home', as: :account_home
  resources :transactions

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_attached_file :image, styles: { medium: '200x300>', thumb: '100x150>', large: '400x600>' }, default_url: ':style/missing.png'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  has_many :book_review

  searchable do
    text :title, :default_boost => 2
    text :author, :default_boost => 2

    string :isbn
    string :owner_email
    string :image_file_name

    time    :due_date
    time    :updated_at

    string  :sort_title do
      title.downcase.gsub(/^(an?|the)/, '')
    end
  end

  handle_asynchronously :solr_index, queue: 'indexing', priority: 50
  handle_asynchronously :solr_index!, queue: 'indexing', priority: 50
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:show]

  # GET /books
  # GET /books.json
  def index
    list = Book.search do
      with(:owner_email, current_user.email)
      order_by(:updated_at, :desc)
      paginate :page => params[:page], :per_page => 10
    end
    @books = list.results
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @reviews = Book.find(@book).book_review.order("created_at DESC") #check index
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    redirect_to @book unless current_user.email == @book.owner_email
  end

  # POST /books
  # POST /books.json
  def create
    Rails.logger.debug("CREATING BOOK")
    @book = Book.new(book_params)
    Rails.logger.debug(" BOOK CREATED due date: #{@book.due_date}")

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if params[:from] == "relist"
          Rails.logger.debug("REACHED HERE 567")
          book_relist = params[:book_relist]
          date = Date.new book_relist["due_date(1i)"].to_i, book_relist["due_date(2i)"].to_i, book_relist["due_date(3i)"].to_i
          @book.update_attribute :due_date, date
          @book.update_attribute :price, params[:price]
          format.html { redirect_to books_url, notice: 'Book was successfully updated.' }
      else
        if @book.update(book_params)
          format.html { redirect_to @book, notice: 'Book was successfully updated.' }
          format.json { render :show, status: :ok, location: @book }
        else
          format.html { render :edit }
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.update_attribute :due_date, DateTime.new(2000,1,1)
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully unlisted.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :isbn, :genre, :condition, :price, :due_date, :comments, :image).merge(owner_email: current_user.email)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book, html: { class: 'form-horizontal'}) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation text-danger">
      <h2><%= pluralize(@book.errors.count, 'error') %> prohibited this book from being saved:</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="form-group">
      <%= f.label :title, class: 'col-lg-1 control-label' %>
      <div class="col-lg-6">
        <%= f.text_field :title, :required => true, class: 'form-control' %>
      </div>
      <div class="col-lg-5">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :author, class: 'col-lg-1 control-label' %>
      <div class="col-lg-6">
        <%= f.text_field :author, :required => true, class: 'form-control' %>
      </div>
      <div class="col-lg-5">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :genre, class: 'col-lg-1 control-label' %>
      <div class="col-lg-6">
        <%= f.select(:genre, ['Action and Adventure', 'Fantasy', 'Mystery', 'Non-fiction', 'Science Fiction', 'Romance', 'Thriller'], :include_blank => true, class: 'form-control') %>
      </div>
      <div class="col-lg-5">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :isbn, 'ISBN', class: 'col-lg-1 control-label' %>
      <div class="col-lg-6">
        <%= f.text_field :isbn, :required => true, class: 'form-control' %>
      </div>
      <div class="col-lg-5">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :condition, class: 'col-lg-1 control-label' %>
      <div class="col-lg-6">
        <%= f.select(:condition, ['New', 'Like New', 'Good', 'Fair', 'Poor'], class: 'form-control') %>
      </div>
      <div class="col-lg-5">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :price, 'Daily Price', class: 'col-lg-1 control-label' %>
      <div class="col-lg-6">
        <div class="input-group">
          <div class="input-group-addon">$</div>
          <%= f.text_field :price, :required => true, maxlength: 6, :class => 'form-control' %>
        </div>
      </div>
      <div class="col-lg-5">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :due_date, class: 'col-lg-1 control-label' %>
      <div class="col-lg-6">
        <%= f.date_select(:due_date, :required => true, :order => [:month, :day, :year], class: 'form-control') %>
      </div>
      <div class="col-lg-5">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :comments, class: 'col-lg-1 control-label' %>
      <div class="col-lg-6">
        <%= f.text_area :comments, class: 'form-control' %>
      </div>
      <div class="col-lg-5">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :image, class: 'col-lg-1 control-label' %>
      <div class="col-lg-6">
        <%= f.file_field :image, :required => false, accept: 'image/png,image/gif,image/jpeg', class: 'btn btn-file' %>
      </div>
      <div class="col-lg-5">
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-11 col-lg-offset-1">
        <%= f.submit :class=> 'btn btn-primary' %>
        <%= link_to 'Back', books_path, class: 'btn btn-warning' %>
      </div>
    </div>

  </fieldset>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

app/views/books/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Your Book Listings</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th style="width: 100px"></th>
      <th></th>
      <th style="width: 160px"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td class="text-center">
          <%= link_to book do %>
              <%= image_tag book.image.url(:thumb) %>
          <% end %>
        </td>
        <td>
          <h4><%= link_to book.title, book %></h4>
          <br> by <%= book.author %>
          <br>
          <% if number_to_currency(book.price) != '$0.00' %>
              <%= number_to_currency(book.price) %> per day
          <% else %>
              Free
          <% end %>
          <br> <%= book.condition %>
          <br>
          <% if book.due_date == DateTime.new(2000,1,1) %>
            Unlisted
          <% else %>
            Due by <%= book.due_date.strftime('%m/%d/%Y') %>
          <% end %>
        </td>
        <td>
          <%= link_to 'Edit', edit_book_path(book), class: 'btn btn-primary' %>
          <% if book.due_date == DateTime.new(2000,1,1) %>
              <div class="modal fade" id=<%= "relistBook#{book.id}" %> tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <h4 class="modal-title"><strong>Relist <%= book.title %></strong></h4>
                    </div>
                    <div class="modal-body">
                      <%= form_tag("/books/update", method: "post", id: "relistBookForm#{book.id}") do %><br/>
                          <%= label_tag(:price, "Daily Price") %>
                          <%= text_field_tag(:price, book.price) %> <br/><br/><br/>
                          <%= label_tag ("Due date:") %>
                          <%= date_select("book_relist", "due_date", order: [:month, :day, :year])%><br/>
                          <%= hidden_field_tag(:from, "relist") %>
                          <%= hidden_field_tag(:id, book.id) %>
                      <% end %>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      <button type="submit" form=<%= "relistBookForm#{book.id}"%> value="Submit" class="btn btn-success">Save</button>
                    </div>
                  </div>
                </div>
              </div>
              <%= link_to "Relist", "#relistBook#{book.id}", "data-toggle" => "modal", class: 'btn btn-success'  %>
          <% else %>
              <%= link_to 'Unlist', book, method: :delete, data: { confirm: 'Are you sure you want to unlist this book?' }, class: 'btn btn-danger'  %>
          <% end %>
        </td>
      </tr>
    <% end %>
  <tr></tr>
  </tbody>
</table>

<%= link_to 'New Book', new_book_path, class: 'btn btn-info'   %>
<div style="text-align: center">
  <%= will_paginate @books, renderer: BootstrapPagination::Rails, inner_window: 1, outer_window: 0%>
</div>

app/views/books/new.html.erb
<h1>New Book Listing</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<!-- <h1> <%=@book.title%> </h1>  -->

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th style="width: 400px"></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
    <tr>
      <td class="text-center">
        <%= image_tag @book.image.url(:large) %>
      </td>
      <td style="font-size:18px">
        <h3><%= @book.title %></h3> 
        <br> <strong>Author:</strong> <%= @book.author %>
        <br> <strong>Genre:</strong> <%= @book.genre %>
        <br> <strong>ISBN:</strong> <%= @book.isbn %>
        <br> <strong>Daily Price:</strong>
        <% if number_to_currency(@book.price) != '$0.00' %>
            <%= number_to_currency(@book.price) %>
        <% else %>
            Free
        <% end %>
        <br> <strong>Condition:</strong> <%= @book.condition %>
        <br> <strong>Due date:</strong> <%= @book.due_date.to_formatted_s(:long) %>
        <br> <strong>Comments:</strong>
        <br> <%= @book.comments %>
      </td>
    </tr>
  </tbody>
</table>

<% if !current_user.nil? %>
  <% if current_user.email == @book.owner_email %>
    <%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-primary' %> &nbsp;
  <% end %>
  <%= link_to 'Your book listings', books_path, class: 'btn btn-default' %>

  <% if current_user.email != @book.owner_email && @book.checked_out == false %>
      <%= form_tag("/transactions/create", method: "post", id: "rentForm", :style => "display: inline") do %>
      <%= hidden_field_tag(:book_id, @book.id) %>
      <button type="submit" form="rentForm" value="Rent" class="btn btn-success">Rent</button>
    <% end %>
  <% elsif current_user.email != @book.owner_email %>
        <a href="#" class="btn btn-danger disabled">Unavailable</a>
  <% end %>
<% end %>

<h4><%= link_to 'Book Reviews', book_reviews_path(@book), class: 'h4' %></h4>
<div class="list-group">
  <% @reviews.each do |review| %>
    <div class="list-group-item">
      <h4 class="list-group-item-heading">
        <% review.rating.times do |i| %>
          <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <% end %>&nbsp;
        <%= review.review %>
      </h4>
      <p class="list-group-item-text">By <%= review.user.name %> on 
      <%= review.created_at.to_formatted_s(:long) %></p>
    </div>
  <% end %>
</div>

<% if !current_user.nil? %>
  <%= link_to 'New Review', new_book_review_path(@book), class: 'btn btn-info'  %>
<% end %>