config/routes.rb
Rails.application.routes.draw do
  get 'balance' => 'balance#index', as: :user_balance

  get 'balance/add'

  get 'balance/remove'
  patch 'balance' => 'balance#update'
  put 'balance' => 'balance#update'

  get 'search/results/' => 'search#results'

  get 'profile/edit' => 'profile#edit'
  get 'profile/:id' => 'profile#show', as: :profile
  get 'profile' => 'profile#redirect'
  patch 'profile/:id' => 'profile#update'

  resources :books do
    resources :reviews
  end
  
  post 'transactions/create/' => 'transactions#create'
  get 'transactions/return_book/' => 'transactions#return_book'
  
  get 'welcome/index'

  devise_for :users

  root 'welcome#index'

  get 'account' => 'account#home', as: :account_home
  resources :transactions

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_book, only: [:index, :new, :create, :destroy]
  before_action :set_review, only: [:show, :destroy]

  def index
    @reviews = Book.find(@book).book_review.order("created_at DESC")
  end

  def show
  end

  def new
    @review = BookReview.new
  end

  def create
    @review = BookReview.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @book, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Review was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:book_id])
    end

    def set_review
      @review = BookReview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:book_review).permit(:rating, :review).merge(user: current_user, book: @book)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for(@review, html: { class: 'form-horizontal'}) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation text-danger">
      <h2><%= pluralize(@review.errors.count, 'error') %> prohibited this review from being saved:</h2>
      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>

    <div class="form-group">
      <%= f.label :rating, class: 'col-lg-1 control-label' %>
      <div class="col-lg-6">
        <%= f.select(:rating, [1,2,3,4,5], class: 'form-control') %>
      </div>
      <div class="col-lg-5">
      </div>
    </div>

    <div class="form-group">
      <%= f.label :review, class: 'col-lg-1 control-label' %>
      <div class="col-lg-6">
        <%= f.text_area :review, class: 'form-control' %>
      </div>
      <div class="col-lg-5">
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-11 col-lg-offset-1">
        <%= f.submit :class=> 'btn btn-primary' %>
        <%= link_to 'Back', book_path(@book), class: 'btn btn-warning' %>
      </div>
    </div>

  </fieldset>
<% end %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @book.title %> Reviews</h1>

<div class="list-group">
  <% @reviews.each do |review| %>
    <div class="list-group-item clearfix">
      <h4 class="list-group-item-heading">
        <% review.rating.times do |i| %>
          <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <% end %>&nbsp;
        <%= review.review %>
      </h4>
      <p class="list-group-item-text">By <%= review.user.name %> on 
      <%= review.created_at.to_formatted_s(:long) %></p>
      <%= link_to 'Delete', book_review_path(review.book, review), method: :delete, class: 'btn btn-sm btn-danger pull-left', data: { confirm: 'Are you sure you want to delete this review?' } %>
    </div>
  <% end %>
</div>

<br>
<%= link_to 'New Review', new_book_review_path, class: 'btn btn-info'  %>
&nbsp;
<%= link_to 'Back to Book Info', book_path(@book), class: 'btn btn-default'  %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

app/views/reviews/show.html.erb
<h1> Your Review </h1>

<div class="container">
  <h4>Book Review</h4>
    <%= @review.rating %>
    <%= @review.review %>
  </div>