config/routes.rb
Rails.application.routes.draw do
  get 'balance' => 'balance#index', as: :user_balance

  get 'balance/add'

  get 'balance/remove'
  patch 'balance' => 'balance#update'
  put 'balance' => 'balance#update'

  get 'search/results/' => 'search#results'

  get 'profile/edit' => 'profile#edit'
  get 'profile/:id' => 'profile#show', as: :profile
  get 'profile' => 'profile#redirect'
  patch 'profile/:id' => 'profile#update'

  resources :books do
    resources :reviews
  end
  
  post 'transactions/create/' => 'transactions#create'
  get 'transactions/return_book/' => 'transactions#return_book'
  
  get 'welcome/index'

  devise_for :users

  root 'welcome#index'

  get 'account' => 'account#home', as: :account_home
  resources :transactions

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.4/flatly/bootstrap.min.css" rel="stylesheet">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
        <title>Airbooks</title>
        <% cache do %>
          <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>
        <% end %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>

    <body>
        <div class="navbar navbar-default navbar-fixed-top">
            <div class="container">
              <div class="navbar-header">
                <a href="/" class="navbar-brand">AirBooks</a>
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
              </div>
              <div class="navbar-collapse collapse" id="navbar-main">
                <ul class="nav navbar-nav navbar-right">
                  <% if user_signed_in? %>
                      <li>
                        <p class="navbar-text" style="color:#ffffff">Logged in as <%= link_to current_user.name, profile_path(current_user), :class => 'navbar-link' %>.</p>
                      </li>
                      <li>
                        <%= link_to 'Your account', account_home_path, :class => 'navbar-link' %>
                      </li>
                      <li>
                        <%= link_to "Post a book listing!", new_book_path, :class => 'navbar-link'  %>
                      </li>
                      <li>
                        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                      </li>
                  <% else %>
                      <li>
                        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
                      </li>
                      <li>
                        <%= link_to "Log in", new_user_session_path, :class => 'navbar-link'  %>
                      </li>
                  <% end %>
                </ul>
              </div>
            </div>
        </div>
        <br/>

        <% if controller_name == 'welcome'%>
          <% @container = 'container-fluid' %>
        <% else %>
          <% @container = 'container' %>
        <% end %>

          <div class = '<%= @container%>'>
            <ul class="nav">
              <li class="active"><a href="/">Home</a></li>
            </ul>

            <% if notice %>
              <p class="alert alert-success"><%= notice %></p>
            <% end %>

            <% if alert %>
              <p class="alert alert-danger"><%= alert %></p>
            <% end %>
            <%= yield %>
          </div>
    </body>
</html>